server:
  servlet:
    context-path: /api
  port: '9999'
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://localhost:5432/parking-control-db
    username: postgres
    password: temperosoft_psql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            nom_contextual_creation: true