server:
  servlet:
    context-path: /api
  port: '9999'
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://localhost:3306/parking-control-db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            nom_contextual_creation: true